BIT2C: Bit2C
BITBAY: BitBay
BITFINEX: Bitfinex
BITFLYER: bitFlyer
BITFLYERFX: bitFlyerFX
BITMARKET: BitMarket
BITSO: Bitso
BITSQUARE: BitSquare
BITSTAMP: Bitstamp
BITTREX: Bittrex
BLEUTRADE: Bleutrade
BTC38: BTC38
BTCC: BTCC
BTCE: BTCE
BTCMARKETS: BTCMarkets
BTCXINDIA: BTCXIndia
BTER: BTER
CCEDK: CCEDK
CEXIO: Cexio
COINBASE: Coinbase
COINCHECK: CoinCheck
COINFLOOR: Coinfloor
COINONE: Coinone
COINSE: Coinse
COINSETTER: Coinsetter
CRYPTOPIA: Cryptopia
CRYPTSY: Cryptsy
ETHERDELTA: EtherDelta
ETHEXINDIA: EthexIndia
GATECOIN: Gatecoin
GEMINI: Gemini
HITBTC: HitBTC
HUOBI: Huobi
ITBIT: itBit
KORBIT: Korbit
KRAKEN: Kraken
LAKEBTC: LakeBTC
LIQUI: Liqui
LIVECOIN: LiveCoin
LOCALBITCOINS: LocalBitcoins
LUNO: Luno
MERCADOBITCOIN: MercadoBitcoin
MONETAGO: MonetaGo
OKCOIN: OKCoin
PAYMIUM: Paymium
POLONIEX: Poloniex
QUADRIGACX: QuadrigaCX
QUOINE: Quoine
THEROCKTRADING: TheRockTrading
TIDEX: Tidex
UNOCOIN: Unocoin
VAULTORO: Vaultoro
YACUNA: Yacuna
YOBIT: Yobit
YUNBI: Yunbi
